Add lambdified functions to the Python linecache
This allows things like inspect.getsource (?? in IPython) to work, and the
code will show up in the tracebacks in IPython.

Presently, the docstring is not included in the source code, because it is
added after the function is execed.

Example:

In [1]: f = lambdify(x, 1/x)

In [2]: f(0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call
last)
<ipython-input-2-6bfbdbfff9c4> in <module>()
----> 1 f(0)

~/venv/dev/lib/python3.5/site-packages/numpy/__init__.py in
<lambda>(_Dummy_15)
----> 1 lambda _Dummy_15: (1/_Dummy_15)

ZeroDivisionError: division by zero

In [3]: f??
Signature: f(_Dummy_15)
Docstring: Created with lambdify.
Source:    lambda _Dummy_15: (1/_Dummy_15)
File:      ~/src/diofant/<lambdifygenerated-1>
Type:      function

// edited by skirpichev

* Expression and signature were removed from docstring.
* update LICENSE